POSTGRES_PASSWORD=judge0password
POSTGRES_USER=judge0user
POSTGRES_DB=judge0db
POSTGRES_HOST=code-sync-postgres

REDIS_HOST=code-sync-redis

JWT_SECRET=judge0secretkey123456789

RUNNER_PORT=3000

DISABLE_DATABASE_ENVIRONMENT_CHECK=1