services:
  - type: web
    name: code-syncer
    runtime: node
    buildCommand: npm install && cd client && npm install && npm run build && cd ../server && npm install && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: JUDGE0_URL
        value: https://ce.judge0.com
